### ISSUE TITLE
Public imagery

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/public#1]
> **Last updated**: Jul 30, 2023

**Description**
Public imagery.

**Tasks**
- [x] Create and close issue.

**Reference(s)**
- [x] lepagebond/lepagebond#1.
- [x] lepageestate/lepageestate#1.
- [x] bibliotheque1/bibliotheque#5.
- [x] [Simple Icons](https://simpleicons.org/).
- [x] [Simpleicons.Vercel.App](https://simpleicons.vercel.app/).

**Comment by guylepage3** [comment]
```
github-guylepage-banner-1600x170
width="840px"
https://user-images.githubusercontent.com/1711854/232258400-cbaa0561-d795-415e-85d0-2c8a9d45ca7d.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232258400-cbaa0561-d795-415e-85d0-2c8a9d45ca7d.svg" width="840px" alt="Guy Lepage banner [1600x170]">

```
github-guylepage-banner-rev-1600x170
width="840px"
https://user-images.githubusercontent.com/1711854/232258402-a9c8f547-4a7f-4a9d-bc13-a8983f65eeda.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232258402-a9c8f547-4a7f-4a9d-bc13-a8983f65eeda.svg" width="840px" alt="Guy Lepage banner [1600x170]">

**Comment by guylepage3** [comment]
Adobe Illustrator  >  Export for Screens  >  Format Settings  >  SVG  >   Font: Convert to Outlines

```
github-guylepage-com-badge-125x27
width="125px"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070532-835405ec-e736-4c04-b6e1-fc8fa7b48088.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070532-835405ec-e736-4c04-b6e1-fc8fa7b48088.svg" width="125px" alt="guylepage.com [125x27]">

```
github-guylepage-com-badge-rev-125x27
width="125px"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070534-65140963-1a6b-469f-85fe-64ec71239732.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070534-65140963-1a6b-469f-85fe-64ec71239732.svg" width="125px" alt="guylepage.com [125x27]">

```
github-x-guylepage3-badge-119x27
width="119px"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070893-e1052112-6773-4f01-b64c-aa7a8cdad905.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070893-e1052112-6773-4f01-b64c-aa7a8cdad905.svg" width="119px" alt="guylepage3 [119x27]">

```
github-x-guylepage3-badge-rev-119x27
width="119px"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070894-4e7d0db1-89ea-4a4d-b849-86d5b8bb2fec.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070894-4e7d0db1-89ea-4a4d-b849-86d5b8bb2fec.svg" width="119px" alt="guylepage3 [119x27]">

----

```
github-lepagebond-com-badge-134x27
width="134px"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070676-c578d481-4cf8-486f-9bc1-a100f5afee50.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070676-c578d481-4cf8-486f-9bc1-a100f5afee50.svg" width="134px" alt="lepagebond.com [134x27]">

```
github-lepagebond-com-badge-rev-134x27
width="134px"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070678-7f55161b-3c24-41af-8bb6-fd0aa8dd5c63.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070678-7f55161b-3c24-41af-8bb6-fd0aa8dd5c63.svg" width="134px" alt="lepagebond.com [134x27]" >

```
github-x-lepagebond-badge-121x27
width="121px"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070988-4bdd20ec-56d8-4c39-8871-ffb2dcea0e50.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070988-4bdd20ec-56d8-4c39-8871-ffb2dcea0e50.svg" width="121px" alt="lepagebond [121x27]">

```
github-x-lepagebond-badge-rev-121x27
width="121px"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070989-3f338be9-a293-4180-8ac7-fdfb51330cb3.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070989-3f338be9-a293-4180-8ac7-fdfb51330cb3.svg" width="121px" alt="lepagebond [121x27]" >

----

```
github-lgg-digital-com-badge-129x27
width="129px"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070767-1a98ae86-2bc5-42ef-af8f-ddb049701d75.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070767-1a98ae86-2bc5-42ef-af8f-ddb049701d75.svg" width="129px" alt="lgg-digital.com [129x27]">

```
github-lgg-digital-com-badge-rev-129x27
width="129px"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070769-30c9b0c9-1949-4ba6-be92-bcc134583719.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257070769-30c9b0c9-1949-4ba6-be92-bcc134583719.svg" width="129px" alt="lgg-digital.com [129x27]" >

```
github-x-lggdigital-badge-112x27
width="112px"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257071097-26ab33b2-36e4-42f9-a1eb-63d5ace6eccb.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257071097-26ab33b2-36e4-42f9-a1eb-63d5ace6eccb.svg" width="112px" alt="lggdigital [112x27]">

```
github-x-lggdigital-badge-rev-112x27
width="112px"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257071098-ff97d0ba-9602-412c-b835-05a31ffb050a.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257071098-ff97d0ba-9602-412c-b835-05a31ffb050a.svg" width="112px" alt="lggdigital [112x27]" >

----

```
github-gestal-10-com-badge-115x27
width="115"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257369777-76b8333d-25c0-483b-be55-eef52255e993.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257369777-76b8333d-25c0-483b-be55-eef52255e993.svg" width="115" alt="gestal-10.com [115x27]">

```
github-gestal-10-com-badge-rev-115x27
width="115"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257369780-d949c03d-6171-48f0-9cce-80665a22a5a3.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257369780-d949c03d-6171-48f0-9cce-80665a22a5a3.svg" width="115" alt="gestal-10.com [115x27]">

```
github-x-gestal-10-badge-102x27
width="102"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257369783-c8defcbe-4875-48f7-88b4-75029573993c.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257369783-c8defcbe-4875-48f7-88b4-75029573993c.svg" width="102" alt="gestal-10 [102x27]">

```
github-x-gestal-10-badge-rev-102x27
width="102"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257369784-2fcda6b3-9066-4ce6-9600-539b7a48b0f6.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257369784-2fcda6b3-9066-4ce6-9600-539b7a48b0f6.svg" width="102" alt="gestal-10 [102x27]" >

**Comment by guylepage3** [comment]
```
github-instagram-badge-113x27
width="113px"
alt="Instagram [113x27]"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257071615-39026d88-75a7-46f3-a0b4-11f84f8a5c95.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257071615-39026d88-75a7-46f3-a0b4-11f84f8a5c95.svg" width="113px" alt="Instagram [113x27]">

```
github-instagram-badge-rev-113x27
width="113px"
alt="Instagram [113x27]"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257071414-e7e45796-cab3-41fb-a383-6c4d1e10e6a9.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257071414-e7e45796-cab3-41fb-a383-6c4d1e10e6a9.svg" width="113px" alt="Instagram [113x27]" >

**Comment by guylepage3** [comment]
```
github-guylepage-wiki-banner-1600x70
width="840px"
https://user-images.githubusercontent.com/1711854/232258209-cafe37ab-d9e6-40a3-a0cf-6ba2d20cb90d.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232258209-cafe37ab-d9e6-40a3-a0cf-6ba2d20cb90d.svg" width="840px" alt="Guy Lepage banner [1600x70]">

```
github-guylepage-wiki-banner-rev-1600x70
width="840px"
https://user-images.githubusercontent.com/1711854/232258210-3d169c6d-2aa9-4d2f-92c9-b816806bd4e6.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232258210-3d169c6d-2aa9-4d2f-92c9-b816806bd4e6.svg" width="840px" alt="Guy Lepage banner [1600x70]">

**Comment by guylepage3** [comment]
```
github-status-production-badge-167x27
width="167px"
alt="Production Status [167x27]"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257077872-5c42c065-2e58-4706-81f6-291a360d8148.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257077872-5c42c065-2e58-4706-81f6-291a360d8148.svg" width="167px" alt="Production Status [167x27]">

```
github-status-production-failing-badge-169x27
width="169px"
alt="Production Failing [169x27]"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257077873-07a8c807-d0ec-42a3-a3c9-76a14884f99f.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257077873-07a8c807-d0ec-42a3-a3c9-76a14884f99f.svg" width="169px" alt="Production Failing [169x27]">

```
github-status-production-passing-badge-174x27
width="174px"
alt="Production Passing [174x27]"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257078018-9c29daed-f463-47fa-afd1-80e5f88b59a3.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257078018-9c29daed-f463-47fa-afd1-80e5f88b59a3.svg" width="174px" alt="Production Passing [174x27]">

**Comment by guylepage3** [comment]
```
github-status-development-ready-badge-172x27
width="172px"
alt="Development Ready [172x27]"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257078164-36cc9db0-47b2-46b1-91bd-977a8f8798a2.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257078164-36cc9db0-47b2-46b1-91bd-977a8f8798a2.svg" width="172px" alt="Development Ready [172x27]">

```
github-status-development-ready-badge-rev-172x27
width="172px"
alt="Development Ready [172x27]"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257089544-3688e381-ad41-44e4-92a5-32701ff74ce5.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257089544-3688e381-ad41-44e4-92a5-32701ff74ce5.svg" width="172px" alt="Development Ready [172x27]">

```
github-status-development-in-progress-badge-211x27
width="211px"
alt="Development In Progress [211x27]"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257078160-009251d7-2920-45a4-be65-d2bf43333694.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257078160-009251d7-2920-45a4-be65-d2bf43333694.svg" width="211px" alt="Development In Progress [211x27]">

```
github-status-development-needs-update-badge-225x27
width="225px"
alt="Development Needs Update! [225x27]"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257078162-f0210d04-0a81-4d7f-9114-717d4e54cfb7.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257078162-f0210d04-0a81-4d7f-9114-717d4e54cfb7.svg" width="225px" alt="Development Needs Update! [225x27]">

```
github-status-development-failing-badge-183x27
width="183px"
alt="Development Failing! [183x27]"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257078158-d91674d2-ee46-4b44-a9a4-86617baa55f8.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257078158-d91674d2-ee46-4b44-a9a4-86617baa55f8.svg" width="183px" alt="Development Failing! [183x27]">

```
github-status-development-passing-badge-184x27
width="184px"
alt="Development Passing [183x27]"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257078163-7ec65dca-9cc0-412e-8a0c-a5d8f26bda42.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/257078163-7ec65dca-9cc0-412e-8a0c-a5d8f26bda42.svg" width="184px" alt="Development Passing [184x27]">

**Comment by guylepage3** [comment]
```
2023-05-02-m3-3360x2100
width="600px"
https://user-images.githubusercontent.com/1711854/235768362-1aed404c-7cb4-4b85-9759-816bdfad3f4f.png
```
<img src="https://user-images.githubusercontent.com/1711854/235768362-1aed404c-7cb4-4b85-9759-816bdfad3f4f.png" width="600px" alt="2023-05-02-m3 [3360x2100]">

**Comment by guylepage3** [comment]
```
github-lepageestate-banner-1600x230
width="100%"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240948021-350659c8-e345-4646-a53f-57eff037be19.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240948021-350659c8-e345-4646-a53f-57eff037be19.svg" width="100%" alt="Lepage Estate banner [1600x230]">

```
github-lepageestate-banner-rev-1600x230
width="100%"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240948029-746d2de9-eba0-48e6-921f-455a9b541ffa.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240948029-746d2de9-eba0-48e6-921f-455a9b541ffa.svg" width="100%" alt="Lepage Estate banner [1600x230]">


```
github-lepageestate-banner-1600x170
width="100%"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240948011-0f60067f-5cf0-4d12-978d-993fc8f761d3.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240948011-0f60067f-5cf0-4d12-978d-993fc8f761d3.svg" width="100%" alt="Lepage Estate banner [1600x170]">

```
github-lepageestate-banner-rev-1600x170
width="100%"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240948026-a3c4822f-94f6-4d83-adc8-c931fe818b85.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240948026-a3c4822f-94f6-4d83-adc8-c931fe818b85.svg" width="100%" alt="Lepage Estate banner [1600x170]">


```
github-lepageestate-banner-1600x70
width="100%"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240948031-68dfce11-2d15-422d-97a1-1321abffbb4a.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240948031-68dfce11-2d15-422d-97a1-1321abffbb4a.svg" width="100%" alt="Lepage Estate banner [1600x70]">

```
github-lepageestate-banner-rev-1600x70
width="100%"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240948035-6b42f81f-01e7-406c-9262-2a645cf9ed3c.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240948035-6b42f81f-01e7-406c-9262-2a645cf9ed3c.svg" width="100%" alt="Lepage Estate banner [1600x70]">

**Comment by guylepage3** [comment]
```
github-lepageestate-crest
width="80px"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240795413-4c764674-5af9-4e7f-afc5-ecc5e0747b8b.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240795413-4c764674-5af9-4e7f-afc5-ecc5e0747b8b.svg" width="80px" alt="Lepage Estate crest">

```
github-lepageestate-crest-rev
width="80px"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240795410-5bede107-d98a-4fed-8ba2-b3ebf57213f7.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240795410-5bede107-d98a-4fed-8ba2-b3ebf57213f7.svg" width="80px" alt="Lepage Estate crest">

**Comment by guylepage3** [comment]
```
github-bibliotheque-banner-1600x230
width="100%"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240993913-010f03d3-6b7b-45cf-bb38-9b47bfca92f3.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240993913-010f03d3-6b7b-45cf-bb38-9b47bfca92f3.svg" width="100%" alt="Bibliotheque banner [1600x230]">

```
github-bibliotheque-banner-rev-1600x230
width="100%"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240993919-7d60a953-59ee-4274-8505-dda8b468189b.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240993919-7d60a953-59ee-4274-8505-dda8b468189b.svg" width="100%" alt="Bibliotheque banner [1600x230]">


```
github-bibliotheque-banner-1600x170
width="100%"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240993903-9df91ccc-576b-46b1-8771-7b7a55703dae.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240993903-9df91ccc-576b-46b1-8771-7b7a55703dae.svg" width="100%" alt="Bibliotheque banner [1600x170]">

```
github-bibliotheque-banner-rev-1600x170
width="100%"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240993918-45df650b-f062-4aac-a144-10e42065955e.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240993918-45df650b-f062-4aac-a144-10e42065955e.svg" width="100%" alt="Bibliotheque banner [1600x170]">


```
github-bibliotheque-banner-1600x70
width="100%"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240993921-3c3df865-fa66-4d60-9b2b-b079784f44a4.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240993921-3c3df865-fa66-4d60-9b2b-b079784f44a4.svg" width="100%" alt="Bibliotheque banner [1600x70]">

```
github-bibliotheque-banner-rev-1600x70
width="100%"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240993924-39d4e0d3-ddf4-4521-8267-f2c4b364b89e.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/240993924-39d4e0d3-ddf4-4521-8267-f2c4b364b89e.svg" width="100%" alt="Bibliotheque banner [1600x70]">

**Comment by guylepage3** [comment]
```
2023-06-07-guylepage3-codebase-vercel-app-2500x1558
width="700px"
alt="2023-06-07-guylepage3-codebase-vercel-app [2500x1558]"
https://github.com/guylepage3/guylepage3/assets/1711854/33ff9caa-2350-4a9b-b470-0b674332a5cb.png
```
<img src="https://github.com/guylepage3/guylepage3/assets/1711854/33ff9caa-2350-4a9b-b470-0b674332a5cb.png" width="700px" alt="2023-06-07-guylepage3-codebase-vercel-app [2500x1558]">

**Comment by guylepage3** [comment]
```
codebase-bug-hex
width="40px"
alt="Codebase bug hex"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/244214091-d931ed75-808c-47aa-a936-d3e0c6cc71ab.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/244214091-d931ed75-808c-47aa-a936-d3e0c6cc71ab.svg" width="40px" alt="Codebase bug hex">

```
codebase-bug-hex-rev
width="40px"
alt="Codebase bug hex"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/244214089-028bd828-935d-4b6e-9e59-d7c5ec7a5389.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/244214089-028bd828-935d-4b6e-9e59-d7c5ec7a5389.svg" width="40px" alt="Codebase bug hex">

**Comment by guylepage3** [comment]
```
codebase-wordmark
width="100px"
alt="Codebase wordmark"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/244215559-93e44e69-eefe-4eed-aea8-4b248758b9b0.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/244215559-93e44e69-eefe-4eed-aea8-4b248758b9b0.svg" width="100px" alt="Codebase wordmark">

```
codebase-wordmark-rev
width="100px"
alt="Codebase wordmark"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/244215539-f260b719-a37c-4073-ab4f-03184db883b4.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/244215539-f260b719-a37c-4073-ab4f-03184db883b4.svg" width="100px" alt="Codebase wordmark">

**Comment by guylepage3** [comment]
```
github-edition-banner-1600x170
width="100%"
alt="Edition banner [1600x170]"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/256639846-dc889b65-075f-4728-a32b-722f855f381c.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/256639846-dc889b65-075f-4728-a32b-722f855f381c.svg" width="100%" alt="Edition banner [1600x170]">

```
github-edition-banner-rev-1600x170
width="100%"
alt="Edition banner [1600x170]"
https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/256640044-ccce7bb0-a697-4f87-8a56-2cd79d41e484.svg
```
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/1711854/256640044-ccce7bb0-a697-4f87-8a56-2cd79d41e484.svg" width="100%" alt="Edition banner [1600x170]">
